---
baseConfig: &BASE_CONFIG
  hiddenToolbarWhenLoading: false #在火箭加载过程中是否隐藏大多数工具栏按钮
  toolbarClassCanDropDown: true #控制应用左上角的设置按钮和班级排课按钮的显示 如果为false设置按钮变为全屏按钮 班级排课按钮隐藏
  showToolbarContent: true #是否显示工具栏非公共部分的功能按钮如工具箱、点名、邀请等功能，如果为false 这部分按钮将被隐藏掉
  isForeignTeacher: false
  showHomeButtonInCourse: true
  showSWFCourse: false
  isSeparateFirst: false
  isRhinoUIPreload: true
  #swf的默认加载方式，false代表bin加载
  isIframeLoad: false #swf 的加载方式，true 为 iframe 加载，false 为 react-components 渲染 <object> 加载
  appLanguage: en_us #语言设置 默认为英文
desktopConfig:
  <<: *BASE_CONFIG
  showHomeButtonInCourse: true
  ifShowSkinsButton: true
  showGroupWidgetMaximumButton: true #控制分组组件关闭按钮和最大化按钮的显示和隐藏 如果为false变为隐藏
  coursewareType: desktop #课件的类型，不要用appType中的值
  needShowToolbarList:
   *ALL_TOOLBAR_LIST
  showSWFCourse: true
  appLanguage: zh_cn

